# Generated by Django 4.1.7 on 2023-03-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('B', 'Bishkek'), ('O', 'Osh'), ('N', 'Naryn'), ('A', 'Batken'), ('I', 'Issyk-kul'), ('D', 'Djalal-abad'), ('T', 'Talas')], max_length=1)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='profile_photo')),
            ],
        ),
    ]
