# Generated by Django 4.1.7 on 2023-03-19 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Имя', 'verbose_name_plural': 'Имени'},
        ),
    ]
