# Generated by Django 4.1.7 on 2023-03-21 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_profile1_foto_profile1_region_profile1_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile1',
            name='region',
            field=models.CharField(choices=[('B', 'Bishkek'), ('O', 'Osh'), ('N', 'Naryn'), ('A', 'Batken'), ('I', 'Issyk-kul'), ('D', 'Djalal-abad'), ('T', 'Talas')], max_length=1),
        ),
        migrations.AlterField(
            model_name='profile1',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
